Fix: all the additional fixes and improvements

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,13 +1,26 @@
 #!/usr/bin/env bash
 
 # THIS IS A SINGULAR INSTALLATION SCRIPT, REGARDLESS OF YOUR OS.
-# It has no dependencies, works find on bash 3.2 (the one that's default on
-# MacOSX).
+# It has no dependencies, and even works with Bash v3.2 (the one that's default on
+# MacOSX), so we're all good.
 
-# This script
-# a) automatically detects your operating system
-# b) downloads the appropriate files for (a)
-# c) untars the download files to temp dirs, installs them, cleans up
+# While performing each component there's dedicated installation function,
+# which may use other shared functions to complement its functionality.
+# In general, each component installation function will do this:
+
+#   a) Detect your operating system
+#   b) Download the appropriate file for your OS.
+#   c) The file will then be un-tarred into its own dir.
+#   d) Perform the necessary installation steps (run execs, copy files, etc.)
+#
+#   f) And, finally, it'll clean up by removing the dir into which the which
+#      the downloaded component was un-tarred
+#
+#      NOTE about (c) - it doesn't delete the .tar files, because why download them
+#      again? Instead, it will nicely ask the user if they wanted to CONTINUE and
+#      then it would untar them, do what it has to do, and rm -rf the directories,
+#      leaving .tar files as is. Since it's all in the /tmp/* directory it'll get
+#      cleaned up eventually, so no big deal.
 
 set -e
 
@@ -17,6 +30,16 @@ Green='\e[0;32m'
 Dim='\033[2m'
 Yellow='\e[33m'
 Cyan='\e[0;36m'
+Bold='\033[1m'
+White='\033[0;37m'
+
+# Colors independent of user settings, we'll prefix them with _
+_White='\033[0;37;256m'
+_Yellow='\e[38;5;226m' # yellow
+_BRed='\e[38;5;9m'
+_On_Black='\e[48;5;16m' # Black background
+_BYellow_OnBlack="${_On_Black}${_Yellow}${Bold}"
+_BRed_OnBlack="${_On_Black}${_BRed}${Bold}"
 NoF='\e[0m' # clear formatting
 
 # This variable is assigned value in which_os() and
@@ -24,13 +47,16 @@ NoF='\e[0m' # clear formatting
 declare myos
 declare myshell
 
+tmp_dir='/tmp/brev-dev' # shared directory for whatever brev downloads
+mkdir -p $tmp_dir
+
 # Helps us download the right versions of brev-cli itself and JetBrains Gateway.
 #
 # TODO: it seems like it makes sense to support cygwin, but I was advised
 # against adding now, because Tailscale breaks it.
 #
 which_os() {
-  [[ -n "$myos" ]] && echo "$os" && return # printing cached value and returning.
+  [[ -n "$myos" ]] && echo "$myos" && return # printing cached value and returning.
   case "$OSTYPE" in
     linux*)  local myos="linux";;
     darwin*) local myos="mac";;
@@ -72,8 +98,9 @@ dl_file() {
   # These two variables are variables for a reason. And sometimes,
   # their content doesn't strictly reflect their names, but it's rather
   # insignificant, so as to bother about it.
-  local hostname="$2"
-  local hostpath="$3"
+  local hostname="$(echo "$2" | sed 's|^/||')"
+  local hostpath="$(echo "$3" | sed 's|^/||')"
+  local url="https://$hostname/$hostpath"
 
   # We'll download the file using whatever program is available, even resorting to
   # telnet in the order in which the variables are listed here. We'll only use
@@ -88,58 +115,55 @@ dl_file() {
   done
 
   case $dl_cmd_name in
-    wget) dl_cmd+=" --show-progress -q -O $fn 'https://$URL_HOST/$URL_PATH'";;
-    curl) dl_cmd+=" -L -O $fn 'https://$URL_HOST/$URL_PATH'";;
+    wget) dl_cmd="wget -O $tmp_dir/$fn $url";;
+    curl) dl_cmd="curl -L -o $tmp_dir/$fn $url";;
+    *)
+      >&2 echo -en "\n${Red}ERROR: you don't have neither ${NoF}curl${Red}"
+      >&2 echo -e "nor ${NoF}wget${Red} installed. Nothing to download files with."
+      >&2 echo -e "Please install one of them\n"
+      exit 1
+      ;;
   esac
 
   # Obviously, ask the user if they wanted to overwrite the file. Maybe not.
-  if [[ -e "$fn" ]]; then
-    echo -e "  ${Yellow}WARNING: file${NoF} $fn ${Yellow}already exists.${NoF}"
-    echo -e "  Would you like to overwrite it? (y/n): "
+  if [[ -e "$tmp_dir/$fn" ]]; then
+    echo -e "  ${Yellow}WARNING: file${NoF} $tmp_dir/$fn ${Yellow}already exists.${NoF}"
+    echo -en "  Would you like to Overwrite it or Continue with the existing one? (y/c): "
     read overwrite_file
     echo "" # extra blank line after the user prompt.
 
     if [[ "$overwrite_file" == "y" ]]; then
-      rm $fn
-      echo "    ${Dim}File${NoF} $fn ${Dim}was removed and will now be downloaded again.${NoF}"
-      echo -e "Running\n\$${Dim}$dl_cmd${NoF}\n"
-      $dl_cmd # <-- ACTUAL PLACE WHERE WE RUN THE COMMAND TO DOWNLOAD THE FILE
-      local download_exit_code=$?
+      rm "$tmp_dir/$fn"
+      echo -e "    ${Dim}File${NoF} $fn ${Dim}was removed and"
+      echo -e "    it will be downloaded again now...${NoF}"
+      $dl_cmd # <-- FIRST PLACE WHERE WE RUN THE COMMAND TO DOWNLOAD THE FILE
+    elif [[ "$overwrite_file" == "c" ]]; then
+      return 0
     else
-      echo 'Okay, will not do anything. Exiting.'
-      exit
+      return 1
     fi
-  fi
-
-  echo -e "    ${Dim} Downloading $fn now...${NoF}"
-
-  if [[ $download_exit_code -gt 0 ]] || [[ -e $fn ]]; then
-    >&2 echo -e "\n${Red}ERROR: file ${White}$fn${Red} has not been downloaded"
-    >&2 echo -e "for some reason OR it has not been downloaded fully."
-    >&2 echo -e "${NoF}\n"
+  else
+    $dl_cmd # <-- THE ONLY OTHER PLACE WE RUN THE COMMAND TO DOWNLOAD
   fi
 
 }
 
 install_jetbrains_gateway() {
+  echo -e "  Downloading and installing ${Blue}JetBrains Gateway${NoF}..."
+  local fn="jetbrains_gateway.tar.gz"
+  local host_name='data.services.jetbrains.com' # https:// added manually. FOR A REASON.
+  local host_path="products/download?code=GW&platform=$(which_os)&type=eap,rc,release,beta"
 
-  echo "  Downloading and installing ${Blue}JetBrains Gateway${NoF}..."
+  dl_file "$fn" "$host_name" "$host_path"
 
-  local fn="./gateway.tar.gz"
-  local url_host='data.services.jetbrains.com' # https:// added manually. FOR A REASON.
-  local url path="products/download?code=GW&platform=$(which_os)&type=eap,rc,release,beta"
-  local fn="$1"
+  echo -e "  ${Dim}Extracting and installing JetBrains gateway...${NoF}"
+  # Longer options for tar, because, see the same comment install_latest()...
+  local untar_dir="$tmp_dir/$(tar \
+    --extract --gzip --verbose --directory="$tmp_dir" --file="$tmp_dir/$fn")"
+  untar_dir="$(echo -e "$untar_dir" | head -n 1)"
 
-  echo -e "   ${Dim}Installing JetBrains Gateway...${NoF}"
-  dl_file "$fn" "$url_host" "$url_path"
-
-
-  echo -e "   ${Dim}Extracting and installing JetBrains gateway...${NoF}"
-  tmp_dir=$(mktemp -d)
-  tar -C "$tmp_dir" -xf gateway.tar.gz && rm "$fn"
-  "$tmp_dir"/*/bin/gateway.sh          && rm -r "$tmp_dir"
-
-  echo -e "${Green}Done.${NoF}"
+  ${untar_dir}bin/gateway.sh 2> $tmp_dir/jetbrains_gw_install_error.log || rm -rf $untar_dir
+  rm -rf $untar_dir
 
 }
 
@@ -147,68 +171,148 @@ install_latest() {
 
   local header="Accept: application/vnd.github.v3.text+json"
   local tags_url="https://api.github.com/repos/brevdev/brev-cli/tags?per_page=1"
-  local dl_url_prefix="https://github.com/brevdev/brev-cli/releases/download/"
 
-  local fetched_tag=$(curl -H "$header" "$tags_url")
-  local tag="$(echo "$fetched_tag" | grep -o 'v\.*' | sed 's/"//g')"
-  local tag_abbr="$(echo "$fetched_tag" | grep -o 'v\.*' | sed 's/v//' | sed 's/"//g')"
-  local fn = "brev-cli_${tag_abbr}_$(which_os)_amd64.tar.gz"
+  # Step 0: getting all info about the latest tag from Github.
+  local fetched_tag=$(curl --silent -H "$header" "$tags_url")
+
+  local tag="$(echo "$fetched_tag"     |\
+    grep -o '"name": ".*"'             |\
+    sed -E 's/"name": "([^"]+)"/\1/')"
+
+  # Basically, losing the preceding "v" with a possible "." char.
+  local tag_abbr="$(echo "$tag" | sed -E 's/^v\.?(.*$)/\1/')"
+  local release_url_path="github.com/brevdev/brev-cli/releases/download/$tag"
 
   local brev_cli_suffix="${tag_abbr}_$(which_os)"
+  local fn="brev-cli_${tag_abbr}_$(which_os)_amd64.tar.gz"
 
   # Step 1: download the file
-  echo -e "   ${Dim}Downloading latest brevdev-cli...${NoF}"
-  dl_file "/tmp/brev/$fn" "$dl_url_prefix" "$fn"
-
+  echo -e "  ${Dim}Downloading latest brevdev-cli $tag...${NoF}"
+  dl_file "$fn" "$release_url_path" "$fn"
 
   # Step 2: untar it into a specially created temporary dir
-  echo -e "   ${Dim}Extracting and installing brevdev-cli...${NoF}"
-  mkdir -p "/tmp/brev/brev-cli_$brev_cli_suffix"
-  tar -xzvf "/tmp/brev/$fn" -C "/tmp/brev/brev-cli_$brev_cli_suffix"
+  echo -e "  ${Dim}Extracting and installing brevdev-cli...${NoF}"
+  local untar_dir="$tmp_dir/brev-cli_${brev_cli_suffix}_amd64"
+
+  mkdir -p $untar_dir
+  # Longer options for tar, because clarity! No one wants to grep the man
+  # pages later, right? ESPECIALLY for `tar`. Just because, tar, yes, just
+  # because, you...
+  #
+  # And here, we're also sending output to /dev/null because we don't need it.
+  # Unlike in the install_jetbrains_gateway() case, we don't need the dir name,
+  # we already know, it's in $untar_dir
+  tar --extract --verbose --gzip \
+    --file="$tmp_dir/$fn" --directory="$untar_dir" > /dev/null
+  # Let's no remove the file, for now. Why download every time?
+  # rm "$tmp_dir/$fn"
 
   # Step 3: inform the user that we are going to place the executable into
   #         the /opt/brev/bin directory and add it to the path. And actually
   #         do it, yes. How dare we.
   brev_bin_dir="/opt/brev/bin"
 
-  echo -e "    ${Yellow}Creating ${Bold}${Cyan}$brev_bin_dir${NoF} for the brevdev"
-  echo -e "    executables. It will automatically added the to the PATH environment"
-  echo -e "    variable (unless it's already present there, of course). Both now and"
-  echo -e "    An appropriate line is also to be added into your $brev_bin_dir.\n"
-  echo -e "      NOTE: both things will be only in case the PATH doesn't currently include"
-  echo -e "      ${Cyan}$brev_bin_dir.${NoF}\n"
+  echo -e  "  ${Yellow}Creating ${Bold}${Cyan}$brev_bin_dir${NoF}${Dim} for the brevdev executables${NoF}"
 
-  echo -e "\n${Bold}It's going to ask to enter your password${NoF}(same as for sudo)"
-  echo -e "so we can create that directory. It would be of great help"
-  echo -e "if you cooperated. Thank you.\n"
-
+  echo -e "  ${Yellow}It MAY ask you to enter your password${NoF}"
+  echo -e "  ${Dim}(same as for sudo) so we can create that directory."
+  echo -e "  It would be of great help if you cooperated. Thank you.${NoF}\n"
 
   # Step 3.1: copy the executable
-  sudo mkdir -p /opt/brev/bin
-  sudo cp /tmp/brev/brev-cli_$brev_cli_suffix/brev /opt/brev/bin
+  sudo mkdir -p $brev_bin_dir
+  sudo cp $untar_dir/brev $brev_bin_dir/
 
-  # Step 3.1: add 
-  if [[ "$(echo "$PATH" | grep -oE "(^|:)$brev_bin_dir:"
-    exp_cmd="export PATH='$brev_bin_dir:$PATH'"
-    $exp_cmd
-    echo -n "$exp_cmd" >> $HOME/.$(which_shell)rc # -n rids us of a newline
+  # If for some reason the file hasn't been copied,
+  # we return 1, which will signal the main program to print an error message.
+  [[ -f $brev_bin_dir/brev ]] || return 1
+
+  # Step 3.2: copy `brev` binary to its desired system destination and add this
+  # destination to $PATH. NOTE: it makes no sense to actually call `export $PATH`
+  # here, because it's bash script. If the user happens to be using zsh, it
+  # would have no effect on him because this script is a child process. As soon
+  # as it exits, variables disappear, exported or not.
+  local shellrc="$HOME/.$(which_shell)rc"
+  if [[ -z "$(echo "$PATH" | grep -oE "(^|:)$brev_bin_dir:")" ]]; then
+
+    echo -e  "  ${Dim}Adding ${Cyan}$brev_bin_dir${White} into the \$PATH variable"
+    echo -e  "  by appending an appropriate line to your $shellrc file.${NoF}\n"
+
+    if [[ -w "$shellrc" ]]; then
+
+      if [[ -z "$(cat "$shellrc" |\
+               grep -E 'PATH="'  |\
+               grep -E "(\"|:)$brev_bin_dir:")"
+        ]]; then
+        # ATTENTION: the following `echo` is not like the other ones. It writes to
+        # a file, so if you'll ever find yourself refactoring this code, this
+        # line shell remain.
+        echo "PATH=\"$brev_bin_dir:\$PATH\"; export PATH" >> \
+          $HOME/.$(which_shell)rc # -n rids us of a newline
+
+        # Now these `echo`s ARE like the other ones... Refactor away.
+        local logout_reminder="Do NOT forget to log out and "
+        logout_reminder+=" log back in again for the changes to take effect."
+
+        echo -e  "  Updated $HOME/.$(which_shell)rc${NoF}"
+        echo -e  "  ${Yellow}${Bold}$(printf '%0.s⠶' $(seq 1 ${#logout_reminder}))${NoF}"
+        echo -en "  ${_BYellow_OnBlack}$logout_reminder${NoF}\n"
+        echo -e  "  ${Yellow}${Bold}$(printf '%0.s⠶' $(seq 1 ${#logout_reminder}))${NoF}"
+      else
+        echo -e  "  ${Dim}\$PATH has already been appropriately updated with"
+        echo -e  "  the $brev_bin_dir directory in your $shellrc file. Nothing to add.${NoF}"
+      fi
+    else
+      >&2 echo -en "  ${_BRed_OnBlack}Cannot update $HOME/.$(which_shell)rc - "
+      >&2 echo -e  "no permission to write to this file or it doesn't exist.${NoF}"
+      >&2 echo -en "  ${Bold}${Yellow}Please add "
+      >&2 echo -e  "${Cyan}$brev_bin_dir${Yellow}${Bold} into the \$PATH variable${NoF}"
+    fi
   fi
 
   # Step 4: Clean up the temporary directory and files
-  echo -e "   ${Dim}Cleaning up the temporary files...${NoF}"
-  rm -rf "/tmp/brev/brev-cli_$suffix"
+  echo -en "  ${Dim}Cleaning up the temporary files..."
+  rm -rf "$untar_dir"
+  echo -e "done.${NoF}"
 
 }
 
 ### THAT'S WHERE THE SCRIPT STARTS
 #
-echo "Installing ${Blue}brev-cli${NoF}..."
-install_latest || exit 1
+echo "Starting the installation process..."
+install_latest
+if [[ $? == 0 ]]; then
+  echo -e "${Green}Installation of brev-cli completed successfully.${NoF}\n"
+else
+  echo -e "${Red}Could not complete brev-cli installation.${NoF}"
+  echo -e "  ${Dim}Check with the error messages above${Dim}\n"
+  exit 1
+fi
 
 # We're installing JetBrains by default, much like the previously existing
 # scripts. The flag -J would tell it NOT TO install JetBrains.
 if [[ ! "${@}" =~ \s-J\s*.*$ ]]; then
   install_jetbrains_gateway
-fi
+  # I tried to do a nice thing the jetbrain's script behavior is non-standard,
+  # it appears. Couldn't properly fetch its STDERR and it seems to just force
+  # the caller script (this one) to exit if there's an error. Not nice,
+  # JetBrains. But user will still get the error message from JetBrains script,
+  # albeit, not as nicely formatted.
+  #
+  # So we're only left with printing this in case of success. But, unfortunately
+  # There isn't any way for us to ensure we delete the temporary files either
+  # in that case. Again. Not a problem, because they're in the /tmp/ dir
+  # and will get cleaned up eventually. Or I find a workaround.
+  if [[ -f $tmp_dir/jetbrains_gw_install_error.log ]]; then
+    # Now we can really tell, whether this program returned an error or not:
+    err="$(cat $tmp_dir/jetbrains_gw_install_error.log | grep -v '^\s*$')"
+    rm $tmp_dir/jetbrains_gw_install_error.log 
 
-echo "${Green}Installation of brevdev-cli completed successfully.${NoF}"
+    if [[ -n "$err" ]]; then
+      echo -e "  ${Red}${Bold}ERROR while installing Jetbrains gateway${NoF}"
+      echo -e "${Red}$(echo -e "$err" | sed 's/^/    /')${NoF}"
+      exit 1
+    fi
+  else
+    echo -e "${Green}Installation of JetBrains Gateway completed successfully.${NoF}"
+  fi
+fi
